# Generated by Django 2.2.6 on 2020-03-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='who_checked_out',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
