# Generated by Django 2.2.6 on 2020-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0002_auto_20200323_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='date_checked_out',
            field=models.DateTimeField(blank='true', null=True),
        ),
    ]
