# Generated by Django 2.2.6 on 2020-03-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0005_auto_20200325_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='this_month_paid',
            new_name='this_period_paid',
        ),
    ]
