# Generated by Django 2.2.6 on 2020-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0006_auto_20200325_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='current_outstanding_balance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='date_paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='date_checked_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
