# Generated by Django 2.2.6 on 2020-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0007_auto_20200325_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='num_currently_checked_out',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
