# Generated by Django 2.2.6 on 2020-03-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0008_auto_20200325_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
