# Generated by Django 2.2.6 on 2020-03-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0009_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
