# Generated by Django 2.2.6 on 2020-03-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0010_auto_20200327_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
