# Generated by Django 2.2.6 on 2020-03-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0011_auto_20200327_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
