# Generated by Django 2.2.6 on 2020-03-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toolshop', '0013_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
